# Generated by Django 5.0.4 on 2025-05-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryvoucher',
            name='article',
            field=models.UUIDField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='entryvoucher',
            name='supplier',
            field=models.UUIDField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='exitrequest',
            name='article',
            field=models.UUIDField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='article',
            field=models.UUIDField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.UUIDField(blank=True, default=None, unique=True),
        ),
    ]
