# Generated by Django 4.2 on 2025-05-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_entryvoucher_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlefamily',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exitrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-13'),
            preserve_default=False,
        ),
    ]
