# Generated by Django 4.2 on 2025-05-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_article_date_articlefamily_date_exitrequest_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitrequest',
            name='applicant',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitvoucher',
            name='applicant',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='applicant',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnvoucher',
            name='applicant',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
